version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskape-rest-api
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    restart: unless-stopped