// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/backendrequests.proto

package taskape_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendRequests_LoginUser_FullMethodName          = "/taskapebackend.BackendRequests/loginUser"
	BackendRequests_VerifyUserToken_FullMethodName    = "/taskapebackend.BackendRequests/verifyUserToken"
	BackendRequests_RegisterNewProfile_FullMethodName = "/taskapebackend.BackendRequests/registerNewProfile"
)

// BackendRequestsClient is the client API for BackendRequests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendRequestsClient interface {
	LoginUser(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	VerifyUserToken(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
	RegisterNewProfile(ctx context.Context, in *RegisterNewProfileRequest, opts ...grpc.CallOption) (*RegisterNewProfileResponse, error)
}

type backendRequestsClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendRequestsClient(cc grpc.ClientConnInterface) BackendRequestsClient {
	return &backendRequestsClient{cc}
}

func (c *backendRequestsClient) LoginUser(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, BackendRequests_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendRequestsClient) VerifyUserToken(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUserResponse)
	err := c.cc.Invoke(ctx, BackendRequests_VerifyUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendRequestsClient) RegisterNewProfile(ctx context.Context, in *RegisterNewProfileRequest, opts ...grpc.CallOption) (*RegisterNewProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNewProfileResponse)
	err := c.cc.Invoke(ctx, BackendRequests_RegisterNewProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendRequestsServer is the server API for BackendRequests service.
// All implementations must embed UnimplementedBackendRequestsServer
// for forward compatibility.
type BackendRequestsServer interface {
	LoginUser(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	VerifyUserToken(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
	RegisterNewProfile(context.Context, *RegisterNewProfileRequest) (*RegisterNewProfileResponse, error)
	mustEmbedUnimplementedBackendRequestsServer()
}

// UnimplementedBackendRequestsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendRequestsServer struct{}

func (UnimplementedBackendRequestsServer) LoginUser(context.Context, *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedBackendRequestsServer) VerifyUserToken(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserToken not implemented")
}
func (UnimplementedBackendRequestsServer) RegisterNewProfile(context.Context, *RegisterNewProfileRequest) (*RegisterNewProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewProfile not implemented")
}
func (UnimplementedBackendRequestsServer) mustEmbedUnimplementedBackendRequestsServer() {}
func (UnimplementedBackendRequestsServer) testEmbeddedByValue()                         {}

// UnsafeBackendRequestsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendRequestsServer will
// result in compilation errors.
type UnsafeBackendRequestsServer interface {
	mustEmbedUnimplementedBackendRequestsServer()
}

func RegisterBackendRequestsServer(s grpc.ServiceRegistrar, srv BackendRequestsServer) {
	// If the following call pancis, it indicates UnimplementedBackendRequestsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendRequests_ServiceDesc, srv)
}

func _BackendRequests_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendRequestsServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendRequests_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendRequestsServer).LoginUser(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendRequests_VerifyUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendRequestsServer).VerifyUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendRequests_VerifyUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendRequestsServer).VerifyUserToken(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendRequests_RegisterNewProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNewProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendRequestsServer).RegisterNewProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendRequests_RegisterNewProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendRequestsServer).RegisterNewProfile(ctx, req.(*RegisterNewProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendRequests_ServiceDesc is the grpc.ServiceDesc for BackendRequests service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendRequests_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskapebackend.BackendRequests",
	HandlerType: (*BackendRequestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "loginUser",
			Handler:    _BackendRequests_LoginUser_Handler,
		},
		{
			MethodName: "verifyUserToken",
			Handler:    _BackendRequests_VerifyUserToken_Handler,
		},
		{
			MethodName: "registerNewProfile",
			Handler:    _BackendRequests_RegisterNewProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/backendrequests.proto",
}
